version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directories:
      - "**/*"
    schedule:
      interval: daily
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/otel*"

  - package-ecosystem: docker
    directory: /tests
    schedule:
      interval: daily
