change:
  - head-branch: ["^change/"]

enhancement:
  - head-branch: ["^feature/", "^feat/", "^enhancement/", "^enh/"]

bug:
  - head-branch: ["^fix/", "^bug/"]

chore:
  - head-branch: ["^chore/"]

tech-debt:
  - head-branch: ["^tech-debt/", "^techdebt/", "^debt/"]

documentation:
  - head-branch: ["^docs/", "^doc/"]
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

dependencies:
  - head-branch:
      ["^deps/", "^dep/", "^dependabot/", "pre-commit-ci-update-config"]
  - changed-files:
      - any-glob-to-any-file: ["go.mod", "go.sum"]

tests:
  - head-branch: ["^tests/", "^test/"]
