name: Fossa

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENSE"

concurrency:
  group: ${{ github.ref_name }}-fossa
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  scan:
    name: Fossa
    runs-on: ubuntu-24.04
    if: ${{ github.event.repository.fork == false }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Scan
        uses: fossas/fossa-action@3ebcea1862c6ffbd5cf1b4d0bd6b3fe7bd6f2cac # v1.7.0
        with:
          api-key: ${{ secrets.FOSSA_TOKEN }}
