name: Fossa

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENSE"

concurrency:
  group: ${{ github.ref_name }}-fossa
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  scan:
    name: Fossa
    runs-on: ubuntu-24.04
    if: ${{ github.event.repository.fork == false }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Scan
        uses: fossas/fossa-action@c0a7d013f84c8ee5e910593186598625513cc1e4 # v1.6.0
        with:
          api-key: ${{ secrets.FOSSA_TOKEN }}
