name: Lint

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-lint
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        directory: [., tests] # we need to run golangci-lint for every module https://github.com/golangci/golangci-lint/issues/828
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Golang Environment
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable

      - name: Lint Go
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          working-directory: ${{ matrix.directory }}
          version: v2.12.2 # renovate: datasource=github-tags depName=golangci/golangci-lint

  actionlint:
    name: Actionlint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint Actions
        uses: reviewdog/action-actionlint@50842263c20a7c46bd0065b9e624d3c569db061e # v1.73
        with:
          actionlint_flags: -shellcheck ""

  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
        with:
          config: .markdownlint-cli2.yaml
          globs: "**/*.md"
          fix: false

  yaml-lint:
    name: YAML lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint YAML
        uses: reviewdog/action-yamllint@e02a49fdf53f51ddd8dfa89b09aa975043aeba38 # v1.23.0
